
name: 52W
on:
  push:
  schedule:
  - cron:  '30 14 * * 0-6'


jobs:
  send_message:
    runs-on: ubuntu-latest
    name: job
    strategy:
      matrix:
        num: [ 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50 ]
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: main
    - name: sender
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: pip install -r ./requirements.txt && python ./main3.py ${{matrix.num}}



